# Generated by Django 5.1.7 on 2025-04-17 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='plant_name',
        ),
    ]
